# Generated by Django 4.2 on 2023-04-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Personnel',
        ),
    ]
