# Generated by Django 4.2 on 2023-04-19 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_rename_user_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='image',
            field=models.ImageField(upload_to='images/personnel'),
        ),
    ]
