# Generated by Django 4.2 on 2023-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_personnel_email_alter_personnel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='phone_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
