# Generated by Django 4.2 on 2023-04-20 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_out', '0002_alter_check_out_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_out',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='check_out',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='check_out',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
