# Generated by Django 4.2 on 2023-05-25 21:15

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', main.models.CustomUserManager()),
            ],
        ),
    ]
