# Generated by Django 4.2 on 2023-05-26 16:52

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.models.CustomUserManager()),
            ],
        ),
    ]
